author: meta1203
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.meta1203.plugins.cryptocashier.payments.CCPayment
name: CC-Payment
startup: postworld
version: '0.1'
